FROM ubuntu:22.04

RUN apt-get update \
  && apt-get install -y \
    ca-certificates \
    curl \
    python3 \
    python-is-python3 \
    python3-pip \
    build-essential \
    git \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade setuptools rosdep rosinstall_generator vcstool
